import { inject, Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { BehaviorSubject, Observable, throwError } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';
import {
  WireframeSchema,
  GeneratedCode,
} from '../models/wireframe.model';
import { CodeGenResponse } from '../models/codegen.model';

@Injectable({ providedIn: 'root' })
export class WireframeService {
  private readonly httpClient = inject(HttpClient);

  private _schema$  = new BehaviorSubject<WireframeSchema | null>(null);
  private _code$    = new BehaviorSubject<GeneratedCode | null>(null);
  private _history$ = new BehaviorSubject<WireframeSchema[]>([]);
  private _loading$ = new BehaviorSubject<boolean>(false);
  private _error$   = new BehaviorSubject<string | null>(null);

  schema$  = this._schema$.asObservable();
  code$    = this._code$.asObservable();
  history$ = this._history$.asObservable();
  loading$ = this._loading$.asObservable();
  error$   = this._error$.asObservable();

  private readonly apiUrl = 'https://localhost:7120/api/ui-generation';

  /**
   * Single AI call that returns both the rendered HTML (for the iframe canvas)
   * and the source code (for the code panel).
   */
  generateWireframe(
    prompt: string,
    imageBase64?: string,
  ): Observable<WireframeSchema> {
    if (!prompt?.trim() && !imageBase64) {
      return throwError(() => new Error('Need a prompt or an image'));
    }

    this._loading$.next(true);
    this._error$.next(null);

    return this.httpClient
      .post<CodeGenResponse>(this.apiUrl, {
        prompt: prompt || '',
        imageBase64: imageBase64 || null,
      })
      .pipe(
        map(res => this.buildSchema(prompt, imageBase64, res)),
        tap(schema => {
          this._schema$.next(schema);
          this._code$.next({
            html: schema.html || '',
            scss: schema.scss || '',
            ts:   this.buildMinimalTs(schema),
          });
          this._loading$.next(false);

          const history = this._history$.getValue();
          this._history$.next([schema, ...history].slice(0, 20));
        }),
        catchError(err => {
          console.error('Generation failed', err);
          this._loading$.next(false);
          this._error$.next(
            'Could not reach the AI server. Is the backend running?',
          );
          return throwError(() => err);
        }),
      );
  }

  /**
   * Backward-compatible no-op-ish wrapper. The code is already generated by
   * `generateWireframe`. If someone still calls this, re-emit from the schema.
   */
  generateCode(schema: WireframeSchema): void {
    if (schema?.html) {
      this._code$.next({
        html: schema.html,
        scss: schema.scss || '',
        ts:   this.buildMinimalTs(schema),
      });
    }
  }

  loadVersion(schema: WireframeSchema): void {
    this._schema$.next(schema);
    if (schema.html) {
      this._code$.next({
        html: schema.html,
        scss: schema.scss || '',
        ts:   this.buildMinimalTs(schema),
      });
    } else {
      this._code$.next(null);
    }
  }

  private buildSchema(
    prompt: string,
    imageBase64: string | undefined,
    res: CodeGenResponse,
  ): WireframeSchema {
    return {
      id: Date.now().toString(),
      name: this.inferName(prompt, !!imageBase64),
      prompt: prompt || 'Image-based generation',
      createdAt: new Date(),
      imageBase64,
      html: res.html,
      scss: res.scss,
      root: { type: 'main' },  // legacy field — not used in iframe mode
    };
  }

  private inferName(prompt: string, hasImage: boolean): string {
    const p = (prompt || '').toLowerCase();
    if (p.includes('dashboard') || p.includes('admin')) return 'Dashboard';
    if (p.includes('login') || p.includes('sign in'))   return 'Login Page';
    if (p.includes('landing') || p.includes('homepage')) return 'Landing Page';
    if (p.includes('form') || p.includes('register'))   return 'Form Screen';
    if (p.includes('profile')) return 'Profile';
    if (p.includes('settings')) return 'Settings';
    if (hasImage)              return 'Generated from Image';
    return 'Generated Screen';
  }

  private buildMinimalTs(schema: WireframeSchema): string {
    const name = (schema.name || 'Generated').replace(/\s+/g, '');
    const selector = (schema.name || 'generated').toLowerCase().replace(/\s+/g, '-');

    return `import { Component } from '@angular/core';

@Component({
  selector: 'app-${selector}',
  templateUrl: './${selector}.component.html',
  styleUrls: ['./${selector}.component.scss']
})
export class ${name}Component { }
`;
  }
}